#!/bin/bash

# Databricks settings
DEFAULT_DATABRICKS_HOST=""
DEFAULT_DATABRICKS_TOKEN=""
DEFAULT_WAREHOUSE_ID=""

# Skyflow settings
DEFAULT_SKYFLOW_VAULT_URL=""
DEFAULT_SKYFLOW_VAULT_ID=""
DEFAULT_SKYFLOW_ACCOUNT_ID=""
DEFAULT_SKYFLOW_BEARER_TOKEN=""

# Group mappings for detokenization
DEFAULT_PLAIN_TEXT_GROUPS="auditor"
DEFAULT_MASKED_GROUPS="customer_service"
DEFAULT_REDACTED_GROUPS="marketing"

# Apply any provided values, otherwise use defaults
export DATABRICKS_HOST=${DATABRICKS_HOST:-$DEFAULT_DATABRICKS_HOST}
export DATABRICKS_TOKEN=${DATABRICKS_TOKEN:-$DEFAULT_DATABRICKS_TOKEN}
export WAREHOUSE_ID=${WAREHOUSE_ID:-$DEFAULT_WAREHOUSE_ID}

export SKYFLOW_VAULT_URL=${SKYFLOW_VAULT_URL:-$DEFAULT_SKYFLOW_VAULT_URL}
export SKYFLOW_VAULT_ID=${SKYFLOW_VAULT_ID:-$DEFAULT_SKYFLOW_VAULT_ID}
export SKYFLOW_ACCOUNT_ID=${SKYFLOW_ACCOUNT_ID:-$DEFAULT_SKYFLOW_ACCOUNT_ID}
export SKYFLOW_BEARER_TOKEN=${SKYFLOW_BEARER_TOKEN:-$DEFAULT_SKYFLOW_BEARER_TOKEN}

export PLAIN_TEXT_GROUPS=${PLAIN_TEXT_GROUPS:-$DEFAULT_PLAIN_TEXT_GROUPS}
export MASKED_GROUPS=${MASKED_GROUPS:-$DEFAULT_MASKED_GROUPS}
export REDACTED_GROUPS=${REDACTED_GROUPS:-$DEFAULT_REDACTED_GROUPS}
